### ISSUE TITLE
Permission issue of schedule for the schedule created by "createScheduleToTriggerGate"

### ISSUE THREAD

**Issue by xiaogangwen** [electric-cloud/EF-Utilities#4]
The permission for the plugin project on flowRuntime is added so that the schedule could approve the gate. But there's chance, which happens in my case, that the pipeline project does not have permission to run procedure in the plugin project which will fail to start the schedule job. This needs to be taken care of as well.

**Comment by lrochette** [comment]
The plugin upon installation should add itself to projects, resources and workspaces systemObjects to be able to run the schedule in your own project

Your own project may also need additional permissions as the schedule will run as the project principal instead of the user starting the pipeline. There is nothing I can do here.

I don't think this is something that needs fixing. le me know if I'm wrong
